api plugin documentation
zurichat/zc_plugin_chessboard pull request #487
Opened 2021-09-09 13:02 UTC by Caesarsage

created a new docs.html file that has all zc_chess plugin backend documentations accessed from the endpoint  - /api/docs/v1

2021-09-09 13:05 UTC, NdubuisiJr commented
No… we can’t use this..

2021-09-09 13:08 UTC, Caesarsage commented
> No… we can’t use this..

state the reasons why please ?

2021-09-09 13:13 UTC, NdubuisiJr commented
Documentation should be generated automatically based on available routes and code documentation…

Something like OpenApi spec or swagger

2021-09-09 13:20 UTC, Caesarsage commented
> Documentation should be generated automatically based on available routes and code documentation…
> 
> Something like OpenApi spec or swagger

oh okay, True. I will use swagger UI then

2021-09-09 20:23 UTC, Caesarsage commented
> > Documentation should be generated automatically based on available routes and code documentation…
> > Something like OpenApi spec or swagger
> 
> oh okay, True. I will use swagger UI then

check this out @NdubuisiJr for a start

2021-09-10 07:54 UTC, NdubuisiJr commented
Okay
I'll look at it now

2021-09-10 08:02 UTC, NdubuisiJr requested changes
Please answer these questions so we can continue?

2021-09-10 09:01 UTC, Caesarsage commented on .idea/inspectionProfiles/profiles_settings.xml
> +<component name="InspectionProjectProfileManager">
these files nor folders are not even in my local system

2021-09-10 09:37 UTC, merged