fetch games by userId
zurichat/zc_plugin_chessboard pull request #506
Opened 2021-09-10 19:33 UTC by mustophy

I made a very little but necessary tweak to the code we created on video call

I also added a seeder folder containing a mock json for our database in case it gets cleared

2021-09-10 20:38 UTC, eni4sure requested changes

2021-09-10 20:38 UTC, eni4sure commented on server/src/routes/v1/game.route.js
>  // Get All Games by User - not implemented -- shauib mustapha
remove the -- not implemented -- comment

2021-09-10 20:38 UTC, eni4sure commented on server/src/controllers/game.controller.js
> +      next(`Unable to fetch user games ${error}`);
check codes above, we've moved back to the custom error class
kindly fix that 
Thanks

2021-09-10 21:03 UTC, eni4sure requested changes

2021-09-10 21:03 UTC, eni4sure commented on server/src/routes/v1/game.route.js
> +router.get("/all/:userId", GameCtrl.getAllByUser);
still leave the comment
just remove the "not implemented" comment 😅

2021-09-10 21:03 UTC, eni4sure commented on server/src/controllers/game.controller.js
> +      throw new CustomError(`Failed to move piece${error}`, 500);
kindly format this error properly - ``piece: ${error}``

2021-09-10 22:18 UTC, NdubuisiJr requested changes
Please add a documentation comment for this route…

2021-09-10 22:18 UTC, NdubuisiJr commented on server/src/routes/v1/game.route.js
> +router.get("/all/:userId", GameCtrl.getAllByUser);
Write the documentation comment for this route…

2021-09-11 08:19 UTC, eni4sure approved these changes

2021-09-11 08:21 UTC, eni4sure commented
CC: @NdubuisiJr kindly approve your change requested is fixed ✔️

2021-09-11 10:14 UTC, NdubuisiJr approved these changes

2021-09-11 10:17 UTC, merged